// This file is auto-generated by @hey-api/openapi-ts

export type RootGetData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/";
};

export type RootGetResponses = {
  /**
   * Successful Response
   */
  200: unknown;
};

export type HealthCheckHealthGetData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/health";
};

export type HealthCheckHealthGetResponses = {
  /**
   * Successful Response
   */
  200: unknown;
};

export type ProtectedRouteProtectedGetData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/protected";
};

export type ProtectedRouteProtectedGetResponses = {
  /**
   * Successful Response
   */
  200: unknown;
};

export type GetUserProfileUserProfileGetData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/user/profile";
};

export type GetUserProfileUserProfileGetResponses = {
  /**
   * Successful Response
   */
  200: unknown;
};

export type GetOpenapiOpenapiJsonGetData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/openapi.json";
};

export type GetOpenapiOpenapiJsonGetResponses = {
  /**
   * Successful Response
   */
  200: unknown;
};

export type ClientOptions = {
  baseUrl: `${string}://${string}` | (string & {});
};
