// This file is auto-generated by @hey-api/openapi-ts

/**
 * HTTPValidationError
 */
export type HttpValidationError = {
  /**
   * Detail
   */
  detail?: Array<ValidationError>;
};

/**
 * ValidationError
 */
export type ValidationError = {
  /**
   * Location
   */
  loc: Array<string | number>;
  /**
   * Message
   */
  msg: string;
  /**
   * Error Type
   */
  type: string;
};

export type RootGetData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/";
};

export type RootGetResponses = {
  /**
   * Successful Response
   */
  200: unknown;
};

export type HealthCheckHealthGetData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/health";
};

export type HealthCheckHealthGetResponses = {
  /**
   * Successful Response
   */
  200: unknown;
};

export type ProtectedRouteProtectedGetData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/protected";
};

export type ProtectedRouteProtectedGetResponses = {
  /**
   * Successful Response
   */
  200: unknown;
};

export type GetUserProfileUserProfileGetData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/user/profile";
};

export type GetUserProfileUserProfileGetResponses = {
  /**
   * Successful Response
   */
  200: unknown;
};

export type ConnectSchwabConnectSchwabPostData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/connect/schwab";
};

export type ConnectSchwabConnectSchwabPostResponses = {
  /**
   * Successful Response
   */
  200: unknown;
};

export type SchwabOauthCallbackApiSchwabCallbackGetData = {
  body?: never;
  path?: never;
  query: {
    /**
     * Code
     */
    code: string;
    /**
     * State
     */
    state: string;
  };
  url: "/api/schwab/callback";
};

export type SchwabOauthCallbackApiSchwabCallbackGetErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type SchwabOauthCallbackApiSchwabCallbackGetError =
  SchwabOauthCallbackApiSchwabCallbackGetErrors[keyof SchwabOauthCallbackApiSchwabCallbackGetErrors];

export type SchwabOauthCallbackApiSchwabCallbackGetResponses = {
  /**
   * Successful Response
   */
  200: unknown;
};

export type DisconnectSchwabDisconnectSchwabDeleteData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/disconnect/schwab";
};

export type DisconnectSchwabDisconnectSchwabDeleteResponses = {
  /**
   * Successful Response
   */
  200: unknown;
};

export type GetOpenapiOpenapiJsonGetData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/openapi.json";
};

export type GetOpenapiOpenapiJsonGetResponses = {
  /**
   * Successful Response
   */
  200: unknown;
};

export type ClientOptions = {
  baseUrl: `${string}://${string}` | (string & {});
};
